function toggleMenu(){document.getElementById("navlinks")?.classList.toggle("show")}
function getCart(){return JSON.parse(localStorage.getItem("koolwalCart")||"[]")}
function saveCart(c){localStorage.setItem("koolwalCart",JSON.stringify(c));updateCartCount()}
function addToCart(id){let c=getCart();c.push(Number(id));saveCart(c);alert("Product added to enquiry cart.");}
function updateCartCount(){document.querySelectorAll("#cartCount").forEach(e=>e.textContent=getCart().length)}
function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-img"><img src="${p.img}" alt="${p.name}"><em>${p.badge}</em></div><div class="card-body"><small>${p.brand}</small><h3>${p.name}</h3><p class="price">₹${p.price} <del>₹${p.mrp}</del></p><span>Wholesale unit: ${p.unit}</span></div></a><button onclick="addToCart(${p.id})">Add to Enquiry Cart</button></article>`}
function renderCategories(targetId="categoryGrid"){let el=document.getElementById(targetId);if(!el)return;el.innerHTML=categories.map(c=>`<a class="category" href="category.html?id=${c.id}"><i>${c.icon}</i><h3>${c.name}</h3><p>${c.desc}</p></a>`).join("")}
function renderProducts(){let el=document.getElementById("productGrid");if(!el)return;let q=(document.getElementById("search")?.value||"").toLowerCase(),cat=document.getElementById("categoryFilter")?.value||"all";el.innerHTML=products.filter(p=>(cat==="all"||p.category===cat)&&(p.name+" "+p.brand).toLowerCase().includes(q)).map(card).join("")||"<p>No products found.</p>"}
function initFilters(){let s=document.getElementById("categoryFilter");if(s)s.innerHTML='<option value="all">All categories</option>'+categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}
function renderCart(){let el=document.getElementById("cartItems");if(!el)return;let c=getCart();if(!c.length){el.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p>Add products to prepare a wholesale enquiry.</p><a class="btn primary" href="products.html">Browse Products</a></div>';return}let rows=c.map((id,i)=>{let p=products.find(x=>x.id===id);return `<div class="cart-row"><img src="${p.img}"><div><b>${p.name}</b><small>${p.brand} • ₹${p.price} / ${p.unit}</small></div><button onclick="removeCart(${i})">Remove</button></div>`}).join("");el.innerHTML=`<div class="cart-list">${rows}</div><a class="btn primary" href="contact.html">Continue to Business Enquiry →</a>`}
function removeCart(i){let c=getCart();c.splice(i,1);saveCart(c);renderCart()}
function renderProduct(){let el=document.getElementById("productDetail");if(!el)return;let id=Number(new URLSearchParams(location.search).get("id")),p=products.find(x=>x.id===id);if(!p){el.innerHTML="<h1>Product not found</h1>";return}el.innerHTML=`<img src="${p.img}" alt="${p.name}"><div><span class="eyebrow">${p.brand}</span><h1>${p.name}</h1><p class="price big">₹${p.price} <del>₹${p.mrp}</del></p><p>Wholesale unit: <b>${p.unit}</b></p><p class="lead">Sample product listing for Koolwal Enterprises. Actual pack sizes, MOQ, stock and final wholesale rates can be confirmed on enquiry.</p><ul><li>Wholesale / distributor supply</li><li>Business enquiries welcome</li><li>MOQ and final quotation on enquiry</li></ul><button class="btn primary" onclick="addToCart(${p.id})">Add to Enquiry Cart</button></div>`}
function renderCategory(){let id=new URLSearchParams(location.search).get("id"),c=categories.find(x=>x.id===id),el=document.getElementById("categoryProducts");if(!el||!c)return;document.getElementById("categoryTitle").textContent=c.icon+" "+c.name;document.getElementById("categoryDesc").textContent=c.desc+". Explore available wholesale products below.";let list=products.filter(p=>p.category===id);el.innerHTML=list.length?list.map(card).join(""):"<p>No sample products in this category yet.</p>"}
function submitEnquiry(e){e.preventDefault();alert("Thank you! Your business enquiry has been captured in this demo.");e.target.reset()}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();renderCategories("homeCategories");renderCategories("categoryGrid");initFilters();renderProducts();renderCart();renderProduct();renderCategory();});